version: "3.9"
services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11431:11434"
    volumes:
      - ./ollama:/root/.ollama
    entrypoint: >
      /bin/sh -c "
        ollama serve &
        sleep 2 &&
        ollama pull gemma3:4b-it-q4_K_M &&
        ollama pull mxbai-embed-large &&
        wait
      "
    restart: unless-stopped

  postgresql:
    image: postgres:13.3
    container_name: postgresql
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped

  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    ports:
      - 9200:9200
      - 9600:9600
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=SoMe12#4_FfF%"
      - "discovery.type=single-node"
      - "plugins.security.disabled=true"
    volumes:
      - ./opensearch/data:/usr/share/opensearch/data
    restart: unless-stopped

  opensearch-dashboards:
    depends_on:
      - opensearch
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    environment:
      - OPENSEARCH_HOSTS='["https://opensearch:9200"]'
      - OPENSEARCH_USERNAME=admin
      - OPENSEARCH_PASSWORD=SoMe12#4_FfF%
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
#    restart: unless-stopped